image: maven:3.6.3-jdk-8-slim

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Ddoclint=none"
  CHANGELOG_FILE: "changelog_v0.9.0.md"
  STAGING_JOBS_ENABLED: "false"
  REMOTE_ST_GITHUB: "git@github.com:st-tu-dresden/bigraph-framework.git"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - branches
  except:
    - /^feature.*$/
  script:
#    - mvn validate -f ./etc/aggregator/pom.xml
    - mvn $MAVEN_CLI_OPTS clean install -U -DskipTests
#    - mvn $MAVEN_CLI_OPTS clean compile

"Running tests":
  stage: test
  only:
    variables:
      - $STAGING_JOBS_ENABLED == "true"
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS test

"Generate Changelog":
  stage: deploy
  only:
    - master
    - ^v[0-9]+(?:.[0-9]+)+$
  image: docker:19.03.0-git
  artifacts:
    name: "bigarts"
    paths:
      - ${CHANGELOG_FILE}
  script:
    - apk update
    - apk add bash
    - ./etc/ci/changelog.sh .mvn/maven.config
#    - cp ${CHANGELOG_FILE} etc/doc/docs/changelogs/

"Generate Documentation":
  stage: deploy
  only:
    variables:
      - $STAGING_JOBS_ENABLED == "true"
    refs:
      - master
      - develop
      - ^v[0-9]+(?:.[0-9]+)+$
  before_script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "dominik.grzelak@tu-dresden.de"
    - git config --global user.name "Dominik Grzelak"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - rm -rf ./documentation/docusaurus/website/build
#    - mvn $MAVEN_CLI_OPTS install exec:java -f documentation/pom.xml
#    - mvn $MAVEN_CLI_OPTS install -Pdistribute
    - mvn install -f documentation/pom.xml -Pdistribute
    - cd ./documentation/docusaurus/website/build/bigraph-framework && git init
    - touch CNAME && echo "www.bigraphs.org" > CNAME
    - git add . && git commit -m "updated documentation"
    - git remote add stgithub $REMOTE_ST_GITHUB
    - git remote -v
    - git push --force stgithub master:gh-pages
# Old approach using git subtree
#    - git add -A
#    - git commit -m "updated github pages"
#    - git subtree push --prefix etc/doc/docusaurus/website/build stgithub gh-pages
#    - git push stgithub master

#"Deploy Artifacts":
#  stage: deploy
#  only:
#    variables:
#      - $STAGING_JOBS_ENABLED == "true"
#    refs:
#      - master
#      - ^v[0-9]+(?:.[0-9]+)+$
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
