image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Ddoclint=none"
  CHANGELOG_FILE: "changelog_v0.6.1-SNAPSHOT.md"

stages:
  - build
  - docgen
#  - test
#  - deploy

build:
  stage: build
  only:
    - branches
  except:
    - /^feature.*$/
  script:
    - echo "skip"
#    - mvn $MAVEN_CLI_OPTS clean compile

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS test

#docs:
# stage: build

changelogs:
  stage: build
  only:
    - master
    - ^v[0-9]+(?:.[0-9]+)+$
  image: docker:19.03.0-git
  artifacts:
    name: "bigarts"
    paths:
      - ${CHANGELOG_FILE}
  script:
    - apk update
    - apk add bash
    - ./etc/ci/changelog.sh .mvn/maven.config
#    - cp ${CHANGELOG_FILE} etc/doc/docs/changelogs/
#    - git push stremotegit master
# https://gitlab.com/gitlab-org/gitlab-foss/issues/18106


docs:
  stage: docgen
#  image: ilyasemenov/gitlab-ci-git-push
#  image: docker:19.03.0-git
  image: maven:3.6.3-jdk-8-slim
  before_script:
    - apt-get update && apt-get install -y git
#    - chmod +x ./etc/ci/prepare_docs.sh
#    - ./etc/ci/prepare_docs.sh
  script:
    - mvn $MAVEN_CLI_OPTS clean install -Pdistribute
    - cd ./etc/ci/
    - git clone https://github.com/PioBeat/bigraphs.git
    - cd ./bigraphs
    - mkdir -p apidocs
    - cp -a ../../../target/site/. ./apidocs/
    - git remote -v
#    - git commit -m "updated github pages"
#    - git push origin gh-pages
#    - git-push user@git.host:repo branch
#deploy:
#  stage: deploy
#  only:
#    - master
#    - ^v[0-9]+(?:.[0-9]+)+$
#    before_script:
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
