image: maven:3.6.3-jdk-8-slim

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Ddoclint=none"
  CHANGELOG_FILE: "changelog_v0.6.1-SNAPSHOT.md"
  JOBS_ENABLED: "false"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - branches
  except:
    - /^feature.*$/
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

"Running tests":
  stage: test
  only:
    variables:
      - $JOBS_ENABLED == "true"
  script:
    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS test

"Generate Changelog":
  stage: deploy
  only:
    - master
    - ^v[0-9]+(?:.[0-9]+)+$
  image: docker:19.03.0-git
  artifacts:
    name: "bigarts"
    paths:
      - ${CHANGELOG_FILE}
  script:
    - apk update
    - apk add bash
    - ./etc/ci/changelog.sh .mvn/maven.config
#    - cp ${CHANGELOG_FILE} etc/doc/docs/changelogs/

"Generate Documentation":
  stage: deploy
  only:
    variables:
      - $JOBS_ENABLED == "true"
    refs:
      - master
      - develop
      - ^v[0-9]+(?:.[0-9]+)+$
  before_script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "dominik.grzelak@tu-dresden.de"
    - git config --global user.name "Dominik Grzelak"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    #    - ./etc/ci/prepare_docs.sh
  script:
    - mvn $MAVEN_CLI_OPTS install -Pdistribute
    - cd ./etc/ci/
    - git clone git@github.com:PioBeat/bigraphs.git
    - git remote -v
    - cd ./bigraphs
    - mkdir -p apidocs
    - cp -a ../../../target/site/apidocs/. ./apidocs/
    - git add -A
    - git commit -m "updated github pages"
    - git push origin gh-pages

#"Deploy Artifacts":
#  stage: deploy
#  only:
#    - master
#    - ^v[0-9]+(?:.[0-9]+)+$
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
