image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Ddoclint=none"
  CHANGELOG_FILE: "changelog.txt"

stages:
  - build
#  - test
#  - deploy

build:
  stage: build
  only: [branches]
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_OPTS $MAVEN_CLI_OPTS test

#docs:
# stage: build

changelogs:
  stage: build
  only: [branches]
  image: docker:19.03.0-git
  artifacts:
    name: "changelog_v0.6-SNAPSHOT.txt"
    paths:
      - ${CHANGELOG_FILE}
  script:
    - ./etc/ci/changelog.sh .mvn/maven.config


#deploy:
#  stage: deploy
#  only:
#    - master
#    - ^v[0-9]+(?:.[0-9]+)+$
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
