{
  "formatVersion": "1.1",
  "component": {
    "group": "it.uniud.mads.jlibbig",
    "module": "jlibbig",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "q6ntahioyndadc5tse6wqb7zm4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jlibbig-0.0.4.jar",
          "url": "jlibbig-0.0.4.jar",
          "size": 11284185,
          "sha512": "ebafaed31a3d83329f7d6498d0af9b69f1d9b5c704318b25645c73c78221c102fc0d321fc70108add0c4ec4ebd1aba5420cb2bf09de939de7f74317de1ab859e",
          "sha256": "c0c9227f2a2229872fe53d6653b0a0c1f9f13efe30d175f1a084380972312447",
          "sha1": "cd6ff88b8a8875b987e6fdf09bc5b472c7945f84",
          "md5": "31502b1a4efb9c04fdc4e6ad26af7f58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.choco-solver",
          "module": "choco-solver",
          "version": {
            "requires": "4.10.6"
          }
        }
      ],
      "files": [
        {
          "name": "jlibbig-0.0.4.jar",
          "url": "jlibbig-0.0.4.jar",
          "size": 11284185,
          "sha512": "ebafaed31a3d83329f7d6498d0af9b69f1d9b5c704318b25645c73c78221c102fc0d321fc70108add0c4ec4ebd1aba5420cb2bf09de939de7f74317de1ab859e",
          "sha256": "c0c9227f2a2229872fe53d6653b0a0c1f9f13efe30d175f1a084380972312447",
          "sha1": "cd6ff88b8a8875b987e6fdf09bc5b472c7945f84",
          "md5": "31502b1a4efb9c04fdc4e6ad26af7f58"
        }
      ]
    }
  ]
}
