<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="F" nsURI="http://www.example.org" nsPrefix="sample">
  <eClassifiers xsi:type="ecore:EClass" name="BPlace" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bChild" upperBound="-1"
        eType="ecore:EClass F.ecore#//BPlace" containment="true" eOpposite="F.ecore#//BPlace/bPrnt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPrnt" eType="ecore:EClass F.ecore#//BPlace"
        eOpposite="F.ecore#//BPlace/bChild"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BRoot" eSuperTypes="F.ecore#//BPlace F.ecore#//IndexableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1"
        eType="ecore:EClass F.ecore#//BBigraph" eOpposite="F.ecore#//BBigraph/bRoots"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BNode" eSuperTypes="F.ecore#//BPlace F.ecore#//NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPorts" upperBound="-1"
        eType="ecore:EClass F.ecore#//BPort" containment="true" eOpposite="F.ecore#//BPort/bNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BSite" eSuperTypes="F.ecore#//BPlace F.ecore#//IndexableType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPoint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bLink" lowerBound="1" eType="ecore:EClass F.ecore#//BLink"
        eOpposite="F.ecore#//BLink/bPoints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BLink" abstract="true" eSuperTypes="F.ecore#//NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPoints" upperBound="-1"
        eType="ecore:EClass F.ecore#//BPoint" eOpposite="F.ecore#//BPoint/bLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPort" eSuperTypes="F.ecore#//BPoint F.ecore#//IndexableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bNode" lowerBound="1" eType="ecore:EClass F.ecore#//BNode"
        eOpposite="F.ecore#//BNode/bPorts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BInnerName" eSuperTypes="F.ecore#//BPoint F.ecore#//NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1"
        eType="ecore:EClass F.ecore#//BBigraph" eOpposite="F.ecore#//BBigraph/bInnerNames"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BEdge" eSuperTypes="F.ecore#//BLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1"
        eType="ecore:EClass F.ecore#//BBigraph" eOpposite="F.ecore#//BBigraph/bEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BOuterName" eSuperTypes="F.ecore#//BLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1"
        eType="ecore:EClass F.ecore#//BBigraph" eOpposite="F.ecore#//BBigraph/bOuterNames"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameableType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexableType" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BBigraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bRoots" upperBound="-1"
        eType="ecore:EClass F.ecore#//BRoot" containment="true" eOpposite="F.ecore#//BRoot/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bEdges" upperBound="-1"
        eType="ecore:EClass F.ecore#//BEdge" containment="true" eOpposite="F.ecore#//BEdge/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bInnerNames" upperBound="-1"
        eType="ecore:EClass F.ecore#//BInnerName" containment="true" eOpposite="F.ecore#//BInnerName/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bOuterNames" upperBound="-1"
        eType="ecore:EClass F.ecore#//BOuterName" containment="true" eOpposite="F.ecore#//BOuterName/bBigraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Printer" eSuperTypes="F.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="F.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="F.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Spool" eSuperTypes="F.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Computer" eSuperTypes="F.ecore#//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Job" eSuperTypes="F.ecore#//BNode"/>
</ecore:EPackage>
