package GCF.original;

import java.io.*;

/**
 *  This class is to centralize the output-management of the framework.
 *  It offers the createOutputFile(String outFile) and the closeOutputFile()-
 *  methods to handle an output File. If no output file is created, the 
 *  standard-output "System.out" is used. Furthermore the methods write() and
 *  writeln() (whichs functionality should be clear) are offered.
 *  The setCurrentDepth()-method is used by the GCF.GXLConnector to let you know,
 *  what the current depth of the abstract Syntax is, so that you can layout
 *  your output accordingly. You can obtain the current depth over the
 *  getCurrentDepth()-method.
 *  For the Use of GXLOutputAPI see class "Demo" and the default-implementations.
 *
 *  IMPORTANT :
 *          You have to copy the GXLOutputAPI into the same directory as your
 *          implementation of the GCF and to rename its package name into the
 *          package name of your implementation.
 */
public class GXLOutputAPI extends Object {

    private static OutputStream out;                // holds the OutputStream
    private static OutputStreamWriter outWriter=new OutputStreamWriter (System.out);
                                                    // holds the OutputStreamWriter (default=System.out)
    private static int currentDepth=0;              // holds the current depth of the abstract syntax tree
                                                    // generated by the GCF.GXLConnector
    
    /** Creates new GXLOutputAPI */
    public GXLOutputAPI() {
    }
    
    /**
     * Creates an FileOutputStream if an outFile is given, otherwise uses System.out as the
     * default outputstream.
     */
    public static void createOutputFile (String outFile) {
        try {
            if (outFile.length()!=0) out = new FileOutputStream(outFile);
            else out=System.out;
            outWriter = new OutputStreamWriter (out);
        }
        catch (java.lang.NullPointerException npe) {
            System.out.println ("NullPointerException occured in GXLOutputAPI!");
        }
        catch (java.io.FileNotFoundException fnfe) { 
            System.out.println ("File "+outFile+" could not be opened/created!");
            System.out.println ("OutputStream changed to System.out !");
            out=System.out;
        } 
    }
    
    /**
     * Writes a String onto the current OutputStream.
     */
    public static void write(String text) {
        try {
            outWriter.write(text,0,text.length());
            outWriter.flush();                      // enforce instant writing of the text
        }
        catch (java.io.IOException ioe) {System.out.print ("ioe");}
        catch (java.lang.NullPointerException npe) {
            System.out.println ("NullPointerException occured in GXLOutputAPI!");
        }
    }
    
    
    /**
     * Writes a String onto the current OutputStream and proceeds to
     * the next line
     */
    public static void writeln (String text) {
        try {
            outWriter.write(text,0,text.length());
            outWriter.write("\r",0,1);
            outWriter.flush();          // enforce instant writing of the text
        }
        catch (java.io.IOException ioe) {
            System.out.println ("IOException occured in GXLOutputAPI!");
        }
        catch (java.lang.NullPointerException npe) {
            System.out.println ("NullPointerException occured in GXLOutputAPI!");
        }
    }
    
    /**
     * Proceeds to the next line in the output file.
     */
    
    public static void writeln () {
        try {
            outWriter.write("\r",0,1);
        }
        catch (java.io.IOException ioe) {
            System.out.println ("IOException occured in GXLOutputAPI!");
        }
        catch (java.lang.NullPointerException npe) {
            System.out.println ("NullPointerException occured in GXLOutputAPI!");
        }
    }
    
    /**
     * Closes the OutputFile.
     */
    public static void closeOutputFile() {
        try {
            outWriter.close();
        }
        catch (java.io.IOException ioe) {
            System.out.println ("Error ! Could not close output file !");
        }
        catch (java.lang.NullPointerException npe) {
            System.out.println ("NullPointerException occured in GXLOutputAPI!");
        }
    }
    
    /**
     * Sets the current depth of the Abstract Syntax Tree generated by the
     * GCF.GXLConnector.
     */
    public static void setCurrentDepth (int depth) {
        currentDepth=depth;
    }
    
    /**
     * Returns the current depth of the Abstract Syntax Tree generated by the
     * GCF.GXLConnector.
     */
    public static int getCurrentDepth () {
        return currentDepth;
    }
}