<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bigraphBaseModel" nsURI="http://de.tudresden.inf.st.bigraphs.models" nsPrefix="bigraphBaseModel">
  <eClassifiers xsi:type="ecore:EClass" name="BPlace" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bChild" upperBound="-1" eType="//BPlace" containment="true" eOpposite="//BPlace/bPrnt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPrnt" eType="//BPlace" eOpposite="//BPlace/bChild"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BRoot" eSuperTypes="//BPlace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BNode">
    <eSuperTypes href="./bookStore.ecore#//BPlace"/>
    <eSuperTypes href="jar:file:/home/dominik/.m2/repository/de/tudresden/inf/st/bigraphs/model/bigraph-ecore-model/2.0/bigraph-ecore-model-2.0.jar!/model/extendedBigraphBaseModel.ecore#//NameableType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPorts" upperBound="-1" eType="//BPort" containment="true" eOpposite="//BPort/bNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BSite" eSuperTypes="//BPlace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPoint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bLink" lowerBound="1" eType="//BLink" eOpposite="//BLink/bPoints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BLink" abstract="true">
    <eSuperTypes href="jar:file:/home/dominik/.m2/repository/de/tudresden/inf/st/bigraphs/model/bigraph-ecore-model/2.0/bigraph-ecore-model-2.0.jar!/model/extendedBigraphBaseModel.ecore#//NameableType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPoints" lowerBound="1" upperBound="-1" eType="//BPoint" eOpposite="//BPoint/bLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPort" eSuperTypes="//BPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bNode" lowerBound="1" eType="//BNode" eOpposite="//BNode/bPorts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BInnerName">
    <eSuperTypes href="./bookStore.ecore#//BPoint"/>
    <eSuperTypes href="jar:file:/home/dominik/.m2/repository/de/tudresden/inf/st/bigraphs/model/bigraph-ecore-model/2.0/bigraph-ecore-model-2.0.jar!/model/extendedBigraphBaseModel.ecore#//NameableType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BEdge" eSuperTypes="//BLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="BOuterName" eSuperTypes="//BLink"/>
</ecore:EPackage>
