<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SAMPLE" nsURI="de.tud.inf.st.bigraphs" nsPrefix="bigraphMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="BPlace" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bChild" upperBound="-1" eType="//BPlace" containment="true" eOpposite="//BPlace/bPrnt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPrnt" eType="//BPlace" eOpposite="//BPlace/bChild"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BRoot" eSuperTypes="//BPlace //IndexableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1" eType="//BBigraph" eOpposite="//BBigraph/bRoots"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BNode" eSuperTypes="//BPlace //NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPorts" upperBound="-1" eType="//BPort" containment="true" eOpposite="//BPort/bNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BSite" eSuperTypes="//BPlace //IndexableType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPoint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bLink" lowerBound="1" eType="//BLink" eOpposite="//BLink/bPoints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BLink" abstract="true" eSuperTypes="//NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bPoints" lowerBound="1" upperBound="-1" eType="//BPoint" eOpposite="//BPoint/bLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPort" eSuperTypes="//BPoint //IndexableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bNode" lowerBound="1" eType="//BNode" eOpposite="//BNode/bPorts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BInnerName" eSuperTypes="//BPoint //NameableType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1" eType="//BBigraph" eOpposite="//BBigraph/bInnerNames"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BEdge" eSuperTypes="//BLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1" eType="//BBigraph" eOpposite="//BBigraph/bEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BOuterName" eSuperTypes="//BLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bBigraph" lowerBound="1" eType="//BBigraph" eOpposite="//BBigraph/bOuterNames"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameableType" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexableType" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BBigraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bRoots" upperBound="-1" eType="//BRoot" containment="true" eOpposite="//BRoot/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bEdges" upperBound="-1" eType="//BEdge" containment="true" eOpposite="//BEdge/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bInnerNames" upperBound="-1" eType="//BInnerName" containment="true" eOpposite="//BInnerName/bBigraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bOuterNames" upperBound="-1" eType="//BOuterName" containment="true" eOpposite="//BOuterName/bBigraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Car" eSuperTypes="//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fuel" eSuperTypes="//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Road" eSuperTypes="//BNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Target" eSuperTypes="//BNode"/>
</ecore:EPackage>
